services:
  api:
    build: .
    command: bash -c "cd src && poe migrate && poe start_prod"
    image: 'api:v1'
    networks:
      - backend
    volumes:
      - ./src:/service/src
    ports:
      - "8080:8080"
    restart: unless-stopped

  api2:
    build: .
    command: bash -c "cd src && poe migrate && uvicorn --factory main.web_api.app:create_app --port 8081 --host 0.0.0.0 --workers 4"
    image: 'api:v1'
    networks:
      - backend
    volumes:
      - ./src:/service/src
    ports:
      - "8081:8081"
    restart: unless-stopped

  web_server:
    image: nginx
    networks:
      - backend
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/postgresql.conf:/usr/share/postgresql/postgresql.conf
    command: -c 'config_file=/usr/share/postgresql/postgresql.conf'
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    networks:
      - backend
    ports:
      - "6432:6432"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./config/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./config/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend: