services:
  api:
    build: .
    image: 'api:v1'
    networks:
      - backend
    volumes:
      - ./src:/service/src
    restart: unless-stopped

  web_server:
    image: nginx
    networks:
      - backend
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend: